export interface UserList {
    "RoleId": number,
    "FirstName": String,
    "LastName": String,
    "Phone": String,
    "Gender": String,
    "ProfileImage": String,
    "ImageName": String,
    "Password": String,
    "Address": String,
    "StateId": number,
    "CityId": number,
    "DistrictId": number,
    "BlockId": number,
    "PanchayatId": number,
    "WardId": number,
    "IsActive": boolean,
    "CreatedBy": number,
    "CreatedDate": Date,
    "ModifiedBy": number,
    "ModifiedDate": Date,
    "OTP": number,
    "IsAdmin": boolean
}
