export interface EventList {
    "EventId": number,
    "Title": string,
    "Description": string,
    "BannerImage": string,
    "BannerImageName": string,
    "StartDate": string,
    "EndDate": string,
    "StateId": number,
    "DistrictId": number,
    "BlockId": number,
    "PanchayatId": number,
    "Publish": boolean,
    "Interested": number,
    "Attendee": number,
    "IsActive": boolean,
    "CreatedBy": number,
    "CreatedDate": string,
    "ModifiedBy": number,
    "ModifiedDate": string
}